FROM python:3.7-alpine
WORKDIR /code
COPY . .
#CMD ["sleep", "${SEC_TO_SLEEP}"]
CMD ["python", "datanode.py"]
#RUN chmod +x ./start.sh
#ENTRYPOINT ["./start.sh"]
#CMD ["python", "datanode.py"]
#CMD sleep $SEC_TO_SLEEP && python datanode.py